### ISSUE TITLE
OutputStream: fix duration

### ISSUE THREAD

**Issue by valnoel** [mikrosimage/avTranscoder#165]
The current method [OutputStream::getStreamDuration()](https://github.com/mikrosimage/avTranscoder/blob/develop/src/AvTranscoder/stream/OutputStream.cpp#L20) computes the stream duration from the current DTS, i.e. the position of the last written packet.
As the DTS values start at 0, the computed duration does not contain the last packet duration, so the result is not correct.

It is used in the [Transcoder::process()](https://github.com/mikrosimage/avTranscoder/blob/develop/src/AvTranscoder/transcoder/Transcoder.cpp#L257) method to :
* update the process progress, so the progress never really reach the end.
* stop the process if this duration come over the expected output duration, so the output stream can be 1-frame longer than the expected duration.

**Comment by cchampet** [comment]
"The dts sequence can start from any value, there is no special significance to dts 0. At start of playback, the difference between wall clock time and the starting dts is computed, and all future dts are converted to wall clock using that. A video stream with dts=-10, -9, -8, ... is perfectly ok. The difference between successive dts is what is used, the absolute values don't matter."
http://stackoverflow.com/questions/13595288/understanding-pts-and-dts-in-video-frames

The PTS seems to be more appropriate to get output stream duration?
https://www.ffmpeg.org/doxygen/2.1/structAVStream.html#afb080896a72650bcb1e613cbb26ef09b

**Comment by cchampet** [comment]
Warning: AVStream.pts is deprecated in last libavformat versions: 
https://libav.org/doxygen/master/structAVStream.html

**Comment by cchampet** [comment]
Solution:
```
/**
 * Returns the pts of the last muxed packet + its duration
 *
 * the retuned value is undefined when used with a demuxer.
 */
int64_t    av_stream_get_end_pts(const AVStream *st);
```

This is the function used by ffmpeg to get duration of stream:
https://github.com/FFmpeg/FFmpeg/blob/93db2708d3b0bcc1f1d87d23ae8adbedd8ea6660/ffmpeg.c#L1209
