### ISSUE TITLE
Unable to create thumbnail from no extension image file (avtranscoder 0.5.4)

### ISSUE THREAD

**Issue by mguiral** [mikrosimage/avTranscoder#191]
This is working fine with audio and video files but not with images.
We uses pythumbnail.py script to make tumbnail with parameters --width 256 --height 150 -t 0 -i 69945351 -o 69945351_thumb.jpg

**Comment by cchampet** [comment]
I tested with ffmpeg 2.3.3 and I reproduced your problem.

It appears that ffmpeg does not succeed to guess the format of the given image.
The code executed by ffmpeg is [here](https://github.com/FFmpeg/FFmpeg/blob/bc259185cb69c6532232be4b2ad57a70ef7ed946/libavformat/utils.c#L248), on tag 2.3.3.

**Comment by cchampet** [comment]
Same result with ffmpeg-2.4.4

**Comment by cchampet** [comment]
And same thing with master branch of ffmpeg...

**Comment by cchampet** [comment]
I sent a mail to ffmpeg-user@ffmpeg.org mailing list.

**Comment by cchampet** [comment]
It works with the current FFmpeg git head!

**Comment by cchampet** [comment]
FFmpeg [2.5.7](https://github.com/FFmpeg/FFmpeg/releases/tag/n2.5.7) can take jpeg inputs without extension.

**Comment by mguiral** [comment]
@cchampet Yes it works fine with FFmpeg 2.5.7. Thanks a lot for your help
