### ISSUE TITLE
Can avtranscoder return file mime-type ?

### ISSUE THREAD

**Issue by mguiral** [mikrosimage/avTranscoder#193]
Example for a DPX file mime-type must be image/x-dpx

**Comment by cchampet** [comment]
Currently it is not explicitly provided by avtranscoder, but ffmpeg can do that:
https://www.ffmpeg.org/doxygen/2.6/structAVOutputFormat.html#ad94e0c8bd362cb9ffbfc44514481fc75

In c++:
```
inputFile.getFormatContext().getAVOutputFormat().mime_type
```

In bindings:
See next release with a function to get the mime_type!

**Comment by cchampet** [comment]
With this [PR](https://github.com/mikrosimage/avTranscoder/pull/198), you can do:
```
inputFile.getFormatName()
inputFile.getFormatLongName()
inputFile.getFormatMimeType()
```
With a dpx image as input, currently I get this:
```
dpx_pipe
piped dpx sequence
unknown
```

I don't know why ffmpeg cannot get mime type of this DPX... 
@mguiral What do you think of the output?

**Comment by cchampet** [comment]
I cleaned the code of the corresponding PR.
Conclusion: depending on the format, we can get the mime type.
Example, from a mxf file:
```
formatName = mxf
formatLongName = ?
formatMimeType = application/mxf
```
But currently it is not possible to get the mime type of DPX files (it is not possible for all images I have tested).
The work must be done on the ffmpeg side, to provide a mime type for each muxer/demuxer formats.
