### ISSUE TITLE
Wrong audio channelLayout when rewrap video with qtfaststart

### ISSUE THREAD

**Issue by mguiral** [mikrosimage/avTranscoder#253]
I have this problem with version 0.5.11 of avtranscoder

The audio source channelLayout = stereo
The rewrap audio channelLayout = 0 chanels

**Comment by cchampet** [comment]
It seems to work in my environment, with the 0.5.11...
Can we test together with Spaces next Monday?

**Comment by mguiral** [comment]
yes

**Comment by cchampet** [comment]
See PR #254, and the commit d4f2d8f9e5d69f28caeb44bacab1de042a34b3a8
