### ISSUE TITLE
Video thumbnail

### ISSUE THREAD

**Issue by mguiral** [mikrosimage/avTranscoder#29]
It will be very usefull to be able to create video thumbnails. I use the following corresponding FFmpeg command line to generate video thumbnail in another project :

ffmpeg -i <input_video> -an -ss 00:01:03 -an -r 1 -vframes 1 -y -f mjpeg <output_thumbnal_image>

Thanks!

**Comment by fabiencastan** [comment]
@mguiral 
You could also use Tuttle to get support of all input images/videos:
https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/host/thumbnail/ThumbnailDiskCache.hpp#L91
