### ISSUE TITLE
Improve readNextPacket mecanism

### ISSUE THREAD

**Issue by valnoel** [mikrosimage/avTranscoder#49]
In StreamTranscoder, to read a packet from input stream :

1. we call InputStream::readNextPacket, which...
2. calls InputFile::readNextPacket, which...
3. calls InputStream::addPacket (to add unused packet to the InputStreams cache)

Can we avoid this two-way process ?

**Comment by cchampet** [comment]
We cannot avoid this process since it enables to cache stream data and provide an efficient way to unwrap.
