### ISSUE TITLE
Fix loading profiles on Windows

### ISSUE THREAD

**Issue by valnoel** [mikrosimage/avTranscoder#55]
In ProfileLoader, the profile object reference is lost when adding it into the profiles list : 
https://github.com/mikrosimage/avTranscoder/blob/develop/src/AvTranscoder/ProfileLoader.cpp#L96

This point prevents ProfileLoader from loading profiles from files (deployed into share/resource).

**Comment by valnoel** [comment]
Also fix Windows path parsing : 
https://github.com/mikrosimage/avTranscoder/blob/develop/src/AvTranscoder/ProfileLoader.cpp#L49
https://github.com/mikrosimage/avTranscoder/blob/develop/src/AvTranscoder/ProfileLoader.cpp#L58

**Comment by cchampet** [comment]
https://github.com/tuttleofx/TuttleOFX/blob/develop/libraries/tuttle/src/tuttle/host/ofx/OfxhPluginCache.cpp
